config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :lectures do
    member do
      get 'enroll'
    end
    collection do
      get 'authorize'
    end
  end

  resources :users do
    member do
      get 'follow'
      get 'notifications'
    end
    collection do
      get 'mark_notification'
    end
  end

  root to: 'home#index'
  get '/home', to: 'home#show', as: 'user_page'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'
  get 'lectures', to: 'lectures#index'
  get 'speakers', to: 'users#index'
  # resources :users do
  resources :reviews

end

app/models/lecture.rb
class Lecture < ActiveRecord::Base
  geocoded_by :address
  after_validation :geocode
  has_many :enrollments
  has_many :users, through: :enrollments
  belongs_to :user, foreign_key: 'speaker_id'


  def speaker
    User.find(self.speaker_id)
  end

  def self.search(query)
  	where("theme like ?", "%#{query}%")
  end
end

app/controllers/lectures_controller.rb
require 'google/api_client'

class LecturesController < ApplicationController
  before_action :set_lecture, only: [:show, :edit, :update, :destroy, :enroll]
  include LecturesHelper

  # GET /lectures
  # GET /lectures.json
  def index
    @lectures = Lecture.all

    if params[:search]
      @lectures = Lecture.search(params[:search])
    elsif params[:searchNear]
      @lectures = Lecture.near(params[:searchNear], 50)
    else
      @lectures = Lecture.all
    end
  end

  # GET /lectures/1
  # GET /lectures/1.json
  def show
    @speaker = User.find(@lecture.speaker_id)
  end

  # GET /lectures/new
  def new
    @lecture = Lecture.new
  end

  # GET /lectures/1/edit
  def edit
  end

  # POST /lectures
  # POST /lectures.json
  def create
    @lecture = Lecture.new(lecture_params)
    @lecture.speaker_id = params[:lecture][:speaker_id]

    respond_to do |format|
      if @lecture.save
        dispare_notifications

        format.html { redirect_to @lecture, notice: 'Palestra foi criada com sucesso.' }
        format.json { render :show, status: :created, location: @lecture }
      else
        format.html { render :new }
        format.json { render json: @lecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lectures/1
  # PATCH/PUT /lectures/1.json
  def update
    respond_to do |format|
      if @lecture.update(lecture_params)
        format.html { redirect_to @lecture, notice: 'Palestra foi atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @lecture }
      else
        format.html { render :edit }
        format.json { render json: @lecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lectures/1
  # DELETE /lectures/1.json
  def destroy
    @lecture.destroy
    respond_to do |format|
      format.html { redirect_to lectures_url, notice: 'Palestra foi apagada com sucesso.' }
      format.json { head :no_content }
    end
  end

  def authorize
    if params[:code].nil?
      get_token
      session[:lecture_id] = params[:format]
      session[:current_user_id] = params[:current_user_id]
      redirect_to @auth_client.authorization_uri.to_s
    else
      redirect_to controller: 'lectures', action: 'enroll', id: session[:lecture_id], current_user_id: session[:current_user_id], code: params[:code]
    end
  end

  def enroll
    get_token
    event = create_enrollment @lecture
    respond_to do |format|
      if event == "Success"
        format.html { redirect_to @lecture, notice: 'Inscrição feita com sucesso.' }
        format.json { render :show, status: :ok, location: @lecture }
      elsif event == "Not availability"
        format.html { redirect_to @lecture, notice: 'Você já tem um evento cadastrado para este momento.' }
        format.json { render :show, status: :error, location: @lecture }
      else
        format.html { redirect_to @lecture, notice: 'Erro ao criar evento.' }
        format.json { render :show, status: :error, location: @lecture }
      end
    end
  end

  def search_near
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lecture
      @lecture = Lecture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lecture_params
      params.require(:lecture).permit(:title, :theme, :description, :price, :duration, :date, :address)
    end
end

app/helpers/lectures_helper.rb
module LecturesHelper

  @auth_client
  @api_client
  @calendar

  def init_auth_client
    if @auth_client.nil?
      client_secrets = Google::APIClient::ClientSecrets.load
      @auth_client = client_secrets.to_authorization
      @auth_client.update!(
        scope: 'https://www.googleapis.com/auth/calendar',
        access_type: "offline",
        approval_prompt:'force',
        redirect_uri: "http://localhost:3000/lectures/authorize/"
      )
    end
    if @api_client.nil?
      init_api_client
    end
  end

  def init_api_client
    @api_client = Google::APIClient.new
    @calendar = @api_client.discovered_api('calendar', 'v3')
  end

  def get_token
    init_auth_client

    if params[:code].nil?
      return false
    else
      @auth_client.code = params[:code]
      @auth_client.fetch_access_token!
    end

    return true
  end

  def get_time_zone
    zone = @api_client.execute(:api_method => @calendar.calendars.get,
      :authorization => @auth_client,
      :parameters => {
        'field' => "timeZone",
        'calendarId' => 'primary'})
    zone.data.timeZone
  end

  def transform_date lecture
    zone = get_time_zone
    date = lecture.date
    date_transformed = date.in_time_zone(zone).to_datetime

    result_date = DateTime.parse(date.strftime("%d %b %Y %H:%M:%S #{date_transformed.formatted_offset}"))
  end

  def check_availability lecture
    result_date = transform_date lecture

    list = @api_client.execute(:api_method => @calendar.events.list,
      :authorization => @auth_client,
      :parameters => {
        'maxResults' => 20,
        'timeMin' => result_date.to_s,
        'timeMax' => (result_date + lecture.duration.minutes).to_s,
        'calendarId' => 'primary'})

    return list.data.items.count == 0
  end

  def create_enrollment lecture
    unless check_availability lecture
      return "Not availability"
    end

    current_user = User.find params[:current_user_id]
    enrollment = Enrollment.new lecture_id: lecture.id, user_id: current_user.id
    
    if lecture.price == 0
      result_date = transform_date lecture
      
      if create_event lecture, result_date
        enrollment.status = true
      else
        return "Fail"
      end
    end
    
    enrollment.save
    return "Success"
  end

  def create_event lecture, result_date
    new_event = @calendar.events.insert.request_schema.new
    new_event.start = { 'dateTime' => result_date }
    new_event.end = { 'dateTime' => result_date + lecture.duration.minutes}
    new_event.location = 'Location'
    new_event.description = lecture.description
    new_event.summary = lecture.title
    result = @api_client.execute(:api_method => @calendar.events.insert,
      :authorization => @auth_client,
      :parameters => { 'calendarId' => 'primary'},
      :headers => {'Content-Type' => 'application/json'},
      :body_object => new_event)
  end

  def dispare_notifications
    followers = Follower.where(panelist_id: current_user.id).all

    followers.each do |f|
      Notification.create(message: "Nova palestra criada por #{current_user.name}", user_id: f.id)
    end
  end
end

app/views/lectures/_form.html.erb
<div class="container">
  <div class="row">
    <%= form_for(@lecture) do |f| %>
      <%= f.hidden_field :speaker_id, value: session[:user_id] %>
      <% if @lecture.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@lecture.errors.count, "error") %> prohibited this lecture from being saved:</h2>

          <ul>
          <% @lecture.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="input-field">
        <%= f.label :title %><br>
        <%= f.text_field :title %>
      </div>
      <div class="input-field">
        <%= f.label :theme %><br>
        <%= f.text_field :theme %>
      </div>
      <div class="input-field">
        <%= f.label :description %><br>
        <%= f.text_field :description %>
      </div>
      <div class="input-field">
        <%= f.label :address %><br>
        <%= f.text_field :address %>
      </div>
      <div class="input-field">
        <%= f.label :price %><br>
        <%= f.number_field :price %>
      </div>
      <div class="input-field">
        <%= f.label :duration %><br>
        <%= f.number_field :duration %>
      </div>
      <div class="input-field">
        <%= f.label :date %><br>
        <%= f.text_field :date, as: :datepicker%>
      </div>
      <div class="actions">
        <%= f.submit class: 'waves-effect waves-light btn' %>
        <%= link_to 'Voltar', lectures_path, class: "waves-effect waves-light btn" %>
      </div>
    <% end %>
  </div>
</div>

app/views/lectures/edit.html.erb
<div class="container">
  <div class="row">
    <h4>Editar Palestra</h4>
    <%= render 'form' %>
  </div>
</div>

app/views/lectures/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="row">
    <h4>Lista de Palestras</h4>

    <%= form_tag(lectures_path, method: :get) do %>
      <%= text_field_tag 'search', nil, placeholder: 'Digite o tema desejado...' %>
      <%= submit_tag "Procurar" %>
    <% end %>

    <%= form_tag(lectures_path, method: :get) do %>
      <%= text_field_tag 'searchNear', nil, placeholder: 'Digite a localidade desejada...' %>
      <%= submit_tag "Encontrar" %>
    <% end %>

    <table class="highlight responsive-table">
      <thead>
        <tr>
          <th>Título</th>
          <th>Tema</th>
          <th>Palestrante</th>
          <th>Duração</th>
          <th>Preço</th>
          <th>Data</th>
        </tr>
      </thead>
      <tbody>
        <% @lectures.each do |lecture| %>
          <tr>
            <td><%= lecture.title %></td>
            <td><%= lecture.theme %></td>
            <td><%= lecture.speaker.id %></td>
            <td><%= lecture.duration.to_s + (lecture.duration > 1 ? " minutos" : " minuto") %></td>
            <td><%= lecture.price == 0.0 ? "Entrada Franca" : number_to_currency(lecture.price) %></td>
            <td><%= lecture.date %></td>
            <td><%= link_to 'Ver', lecture, class: "waves-effect waves-light btn" %></td>
            <% if lecture.speaker_id == session[:user_id] %>
            <td><%= link_to 'Editar', edit_lecture_path(lecture), class: "waves-effect waves-light light-blue accent-4 btn" %></td>
            <td><%= link_to 'Apagar', lecture, method: :delete, data: { confirm: 'Você tem certeza?' },class: "waves-effect waves-light red accent-4 btn" %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
    <br>
    <%= link_to 'Criar uma palestra', new_lecture_path, class: "waves-effect waves-light btn" %>
    <%= link_to 'Voltar', user_page_path, class: "waves-effect waves-light btn" %>
  </div>
</div>

app/views/lectures/new.html.erb
<div class="container">
  <div class="row">
    <h4>Nova Palestra</h4>

    <%= render 'form' %>

  </div>
</div>

app/views/lectures/show.html.erb
<p id="notice"><%= notice %></p>

<table class="highlight responsive-table">
  <thead>
    <tr>
      <th>Título: </th>
      <th>Tema: </th>
      <th>Descrição: </th>
      <th>Palestrante: </th>
      <th>Endereço: </th>
      <th>Preço: </th>
      <th>Duração: </th>
      <th>Data: </th>
    </tr>
  </thead>
  <tbody>
      <tr>
        <td><%= @lecture.title %></td>
        <td><%= @lecture.theme %></td>
        <td><%= @lecture.description %></td>
        <td><%= @lecture.speaker.name %></td>
        <td><%= @lecture.address %></td>
        <td><%= @lecture.price == 0.0 ? "Entrada Franca" : number_to_currency(@lecture.price) %></td>
        <td><%= @lecture.duration.to_s + (@lecture.duration > 1 ? " minutos" : " minuto") if @lecture.duration%></td>
        <td><%= @lecture.date %></td>
      </tr>
  </tbody>
</table>

<div class="center-align">

  <%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@lecture.latitude}%2C#{@lecture.longitude}" %>
  <br>
  <%if @lecture.price == 0.0 %>
    <%= link_to 'Inscrever-se', authorize_lectures_path(@lecture, current_user_id: current_user.id), class: "waves-effect waves-light light-green btn" %>
  <%else %>
    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.application.secrets.stripe_publishable_key %>"
    data-currency= "BRL"
    data-location= "auto"
    data-description="Pagamento de Palestra"
    data-amount="<%= @lecture.price * 100 %>">
    </script>
  <%end%>
  <%= link_to 'Editar', edit_lecture_path(@lecture), class: "waves-effect light-blue waves-light btn" %>
  <%= link_to 'Voltar', lectures_path , class: "waves-effect waves-light btn"%>
</div>