config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :lectures do
    member do
      get 'enroll'
    end
    collection do
      get 'authorize'
    end
  end

  resources :users do
    member do
      get 'follow'
      get 'notifications'
    end
    collection do
      get 'mark_notification'
    end
  end

  root to: 'home#index'
  get '/home', to: 'home#show', as: 'user_page'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'
  get 'lectures', to: 'lectures#index'
  get 'speakers', to: 'users#index'
  # resources :users do
  resources :reviews

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :enrollments
  has_many :lectures, through: :enrollments
  has_many :notifications
  has_many :followers
  has_many :users, through: :followers, source: :panelist
  has_many :reviews

  def self.omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.email = auth.info.email
      user.image = auth.info.image
      user.token = auth.credentials.token
      user.expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end

  def self.search(query)
    where("name like ?", "%#{query}%")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :notifications, :follow]

  # GET /users
  # GET /users.json
  def index
    if params[:search]
      @users = User.search(params[:search])
    else
      speakers = []
      Lecture.find_each do |lecture|
        speakers.push(lecture.user)
      end
      @users = speakers.uniq
    end
  end

  def notifications
    @notifications = Notification.where(user_id: @user.id, displayed: false).all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end


  def mark_notification
    notification = Notification.find params[:notification_id]
    notification.displayed = true

    respond_to do |format|
      if notification.save
        format.html { redirect_to notifications_user_url(id: current_user.id), notice: 'Notificação lida.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { redirect_to notifications_user_url(id: current_user.id), notice: 'Erro.' }
        format.json { render :show, status: :error, location: @user }
      end
    end
  end

  def follow
    current_user = User.find(params[:current_user_id])

    respond_to do |format|
      if current_user.id != @user.id
        Follower.create panelist_id: @user.id, user_id: current_user.id

        format.html { redirect_to @user, notice: 'Você está seguindo este usuário.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { redirect_to @user, notice: 'Você não pode seguir a si mesmo.' }
        format.json { render :show, status: :error, location: @user }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params[:user]
      params.require(:user).permit(:provider, :uid, :name,:image,:token,:expires_at,:review_id,:email)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="row">
    <h4>Lista de Palestrantes</h4>

    <%= form_tag(users_path, method: :get) do %>
      <%= text_field_tag 'search', nil, placeholder: 'Digite o nome do palestrante...' %>
      <%= submit_tag "Procurar" %>
    <% end %>

    <table class="highlight responsive-table">
      <thead>
        <tr>
          <th>Nome do Palestrante</th>
          <th>Nota</th>
        </tr>
      </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.rate %></td>
        <td><%= link_to 'Ver', user, class: "waves-effect waves-light btn" %></td>
      </tr>
    <% end %>
  </tbody>
  </table>
  </div>
  <%= link_to 'Voltar', user_page_path, class: "waves-effect waves-light btn" %>
</div>

app/views/users/notifications.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Notifications</h1>

<table>
  <thead>
    <tr>
      <th>Mensagem</th>
    </tr>
  </thead>

  <tbody>
    <% @notifications.each do |notification| %>
      <tr>
        <td><%= notification.message %></td>
        <td><%= link_to 'Marcar como lida', mark_notification_users_path(notification_id: notification.id) %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

    <table class="highlight responsive-table">
      <thead>
        <tr>
          <th>Nome do Palestrante</th>
        </tr>
      </thead>
  <tbody>
      <tr>
        <td><%= @user.name %></td>
        <td><%= link_to 'Avaliar este Palestrante', new_review_path(id: @user), class: "waves-effect waves-light btn" %>
        <%= link_to 'Seguir', follow_user_path(@user, current_user_id: current_user.id), class: "waves-effect waves-light btn" %></td>
      </tr>
  </tbody>
</table>
    <table class="highlight responsive-table">
      <thead>
        <tr>
          <th>Título</th>
          <th>Tema</th>
          <th>Duração</th>
          <th>Preço</th>
          <th>Data</th>
        </tr>
      </thead>
      <tbody>
        <% @user.lectures.each do |lecture| %>
          <tr>
            <td><%= lecture.title %></td>
            <td><%= lecture.theme %></td>
            <td><%= lecture.duration.to_s + (lecture.duration > 1 ? " minutos" : " minuto") %></td>
            <td><%= lecture.price == 0.0 ? "Entrada Franca" : number_to_currency(lecture.price) %></td>
            <td><%= lecture.date %></td>
            <td><%= link_to 'Ver', lecture, class: "waves-effect waves-light btn" %></td>
            <% if lecture.speaker_id == session[:user_id] %>
            <td><%= link_to 'Editar', edit_lecture_path(lecture), class: "waves-effect waves-light light-blue accent-4 btn" %></td>
            <td><%= link_to 'Apagar', lecture, method: :delete, data: { confirm: 'Você tem certeza?' },class: "waves-effect waves-light red accent-4 btn" %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
<%= link_to 'Voltar', users_path, class: "waves-effect waves-light btn" %>