config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :lectures do
    member do
      get 'enroll'
    end
    collection do
      get 'authorize'
    end
  end

  resources :users do
    member do
      get 'follow'
      get 'notifications'
    end
    collection do
      get 'mark_notification'
    end
  end

  root to: 'home#index'
  get '/home', to: 'home#show', as: 'user_page'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'
  get 'lectures', to: 'lectures#index'
  get 'speakers', to: 'users#index'
  # resources :users do
  resources :reviews

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def show
  	@user = User.find_by_id session[:user_id]
  	
    if @user.lectures.count == 0
      ranking_lecturers
    else
      self.recomendation_lecturers
    end
  end

  def ranking_lecturers
    @users = User.order(:rate).limit(5).where.not(id: @user.id).reverse
  end

  def recomendation_lecturers
    lecturers_ranked = []

    @user.lectures(limit: 5).reverse.each do |user_lecture| 
      Lecture.find_each do |lecture|
        if lecture.title == user_lecture.title
          if lecture.user != @user
            lecturers_ranked.push(lecture.user)
          end
        end
      end
    end
    lecturers_ranked = lecturers_ranked.uniq
    @users = lecturers_ranked.sort_by {|obj| obj.rate}.reverse
  end
    
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div id="index-banner" class="parallax-container">
  <div class="section no-pad-bot">
    <div class="container">
      <br><br>
      <h1 class="header center text-accent-4">Portal de Palestras</h1>
      <div class="row center">
        <h5 class="header col s12 light">Um portal desenvolvido de alunos para alunos</h5>
      </div>
      <div class="row center">
        <a href="/login" class="waves-effect waves-light btn"><i class="material-icons left">person_pin</i>Comece Agora</a>
      </div>
    </div>
  </div>
  <div class="parallax"><img src="assets/background1.png" alt="Unsplashed background img 1"></div>
</div>

<div class="container">
  <div class="section">

    <!--   Icon Section   -->
    <div class="row">
      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center brown-text"><i class="material-icons">flash_on</i></h2>
          <h5 class="center">Aprenda mais rápido</h5>

          <p class="light">Encontre todas as palestras e video aulas do seus temas favoritos. Aprenda com os melhores profissionais do mercado. Destaque-se em meio a multidão</p>
        </div>
      </div>

      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center brown-text"><i class="material-icons">group</i></h2>
          <h5 class="center">Focado Na Experiência de Usuário</h5>

          <p class="light">O Portal de Palestras tem como objetivo facilitar para que você encontre o mais rápdo possível as palestas que você deseja. Encontre, assista e aprenda com facilidade!</p>
        </div>
      </div>

      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center brown-text"><i class="material-icons">settings</i></h2>
          <h5 class="center">Fácil de Usar</h5>

          <p class="light">Pensamos em tudo por você. Com apenas alguns cliques encontre sua palestra e indique para seus amigos</p>
        </div>
      </div>
    </div>

  </div>
</div>


<div class="parallax-container valign-wrapper">
  <div class="section no-pad-bot">
    <div class="container">
      <div class="row center">
        <h5 class="header col s12 light">Aprenda com os melhores profissionais do mercado</h5>
      </div>
    </div>
  </div>
  <div class="parallax"><img src="assets/background2.png" alt="Unsplashed background img 2"></div>
</div>

<div class="container">
  <div class="section">

    <div class="row">
      <div class="col s12 center">
        <h3><i class="mdi-content-send brown-text"></i></h3>
        <h4>Nos ajude a crescer</h4>
        <p class="left-align light">Compartilhe suas palestras favoritas nas suas redes sociais favoritas, indique amigos e ganhe descontos nas compras das próximas palestras;</p>
      </div>
    </div>

  </div>
</div>

<div class="parallax-container valign-wrapper">
  <div class="section no-pad-bot">
    <div class="container">
      <div class="row center">
        <h5 class="header col s12 light">Profissionalize-se: use o conhecimento adquirido para buscar novas oportunidades</h5>
      </div>
    </div>
  </div>
  <div class="parallax"><img src="assets/background3.png" alt="Unsplashed background img 3"></div>
</div>

<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Biografia</h5>
        <p class="grey-text text-lighten-4">Projeto desenvolvido por um time de estudantes do curso de Engenharia de Software da Universidade de Brasília para a diciplina de Desenvolvimento Avançado de Software</p>

      </div>
      <div class="col l3 s12">
        <h5 class="white-text">Configurações</h5>
        <ul>
          <li><a class="white-text" href="#!">Link 1</a></li>
        </ul>
      </div>
      <div class="col l3 s12">
        <h5 class="white-text">Conecte-se</h5>
        <ul>
          <li><a class="white-text" href="#!">Link 1</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    Feito com <a class="brown-text text-lighten-3" href="http://materializecss.com">Materialize</a>
    </div>
  </div>
</footer>

app/views/home/show.html.erb
<div class="container">
  <div class="row">
    <div class="col s12 m9 l10">
      <div id="lectures" class="section scrollspy">
        <% if current_user.lectures.empty? %>
          <div class="container">
            <div class="row center">
              <h5 class="header col s12 light">Você ainda não se matriculou em nenhuma palestra, comece por aqui.</h5>
              <a href="/lectures" class="waves-effect waves-light btn"><i class="material-icons left">cloud</i>Ver Palestras</a>
              <a href="/speakers" class="waves-effect waves-light btn"><i class="material-icons left">cloud</i>Ver Palestrantes</a>
            </div>
          </div>
        <% else %>
          <p>
            <h4>Minhas Palestras</h4>
            <table>
              <thead>
                <tr>
                  <th data-field="title">Título</th>
                  <th data-field="date">Data</th>
                  <th data-field="price">Preço</th>
                </tr>
              </thead>
              <% current_user.lectures.each do |lecture| %>
                <tbody>
                  <tr>
                    <td><%= lecture.title %></td>
                    <td><%= lecture.date %></td>
                    <td><%= lecture.price == 0.0 ? "Entrada Franca" : number_to_currency(lecture.price) %></td>
                    <td><%= link_to 'Saiba Mais', lecture, class: "waves-effect waves-light btn" %></td>
                  </tr>
                </tbody>
              <% end %>
            </table>
          </p>
          <a href="/lectures" class="waves-effect waves-light btn"><i class="material-icons left">cloud</i>Procurar Mais Palestras</a>
        <% end %>
      </div>
      <div id="recomendations" class="section scrollspy container">
        <h4>Recomendado pra você</h4>
        <p>
        <table class="highlight responsive-table">
        <thead>
          <tr>
            <th>Nome do Palestrante</th>
            <th>Nota</th>
          </tr>
        </thead>

          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= user.name %></td>
                <td><%= user.rate %></td>
                <td><%= link_to 'Ver', user, class: "waves-effect waves-light btn" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </p>
      <a href="/speakers" class="waves-effect waves-light btn"><i class="material-icons left">cloud</i>Ver Mais Palestrantes</a>
      </div>
      <% if @user.email.include? 'gmail' %>
      <div id="calendar" class="section scrollspy container">
        <iframe src="https://calendar.google.com/calendar/embed?src=<%=@user.email%>&ctz=America/Sao_Paulo" style="border: 0" width="800" height="600" frameborder="0" scrolling="no"></iframe>
      </div>
      <% end %>
      <div id="nearlectures" class="section scrollspy container">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. </p>
      </div>
    </div>
    <div class="col hide-on-small-only m3 l2">
      <ul class="section table-of-contents">
        <li><a href="#lectures">Minhas Palestras</a></li>
        <li><a href="#recomendations">Recomendações</a></li>
        <li><%= link_to 'Notificações', notifications_user_path(id: current_user.id) %></li>
        <% if @user.email.include? 'gmail' %>
        <li><a href="#calendar">Calendário</a></li>
        <% end %>
        <li><a href="#nearlectures">Palestras Próximas</a></li>
      </ul>
    </div>
  </div>
</div>